services:
  db:
    image: postgres:latest
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - 'blog-postgres:/var/lib/postgresql/data'
    networks:
      - blog-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: blog-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8082:80"
    networks:
      - blog-network
    depends_on:
      - db

volumes:
  blog-postgres:
    driver: local

networks:
  blog-network:
    driver: bridge
    external: true
    name: blog-network